version: "3.9"

services:
  app:
    build: ./fieldbase-frontend
    volumes:
      - ./fieldbase-frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - BROWSER=${BROWSER}
  server:
    build: ./fieldbase-backend
    volumes:
      - ./fieldbase-backend:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}

  db:
    image: mongo:4.4.13
    restart: always
